### ISSUE TITLE
java.lang.IllegalArgumentException: Service not registered

### ISSUE THREAD

**Issue by gotev** [gotev/android-speech#4]
``` java
java.lang.IllegalArgumentException: Service not registered: android.speech.SpeechRecognizer$Connection@367945c4
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1094)
       at android.app.ContextImpl.unbindService(ContextImpl.java:2000)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:558)
       at android.speech.SpeechRecognizer.destroy(SpeechRecognizer.java:408)
       at net.gotev.speech.Speech.initSpeechRecognizer(Speech.java:262)
       at net.gotev.speech.Speech.returnPartialResultsAndRecreateSpeechRecognizer(Speech.java:471)
       at net.gotev.speech.Speech.stopListening(Speech.java:442)
       at net.igenius.crystal.view.activity.AdvisorActivity.stopSpeech(AdvisorActivity.java:228)
```

**Comment by AgNm** [comment]
any update on this?

**Comment by praharshbhatt** [comment]
Having the same issue

**Comment by gotev** [comment]
Which version are you using?
