### ISSUE TITLE
SpeechRecognitionException: 7 - No recognition result matched. Try turning on partial results as a workaround.

### ISSUE THREAD

**Issue by TinySonhh** [gotev/android-speech#60]
Hi,

Recently, I faced this error on Android 11

net.gotev.speech.SpeechRecognitionException: 7 - No recognition result matched. Try turning on partial results as a workaround.
at net.gotev.speech.engine.BaseSpeechRecognitionEngine.onError(BaseSpeechRecognitionEngine.java:156)
at android.speech.SpeechRecognizer$InternalListener$1.handleMessage(SpeechRecognizer.java:453)
at android.os.Handler.dispatchMessage(Handler.java:106)

**Triggered**
onStartOfSpeech
onSpeechRmsChanged
onSpeechResult (no result data)

**not triggered**
onSpeechPartialResults

Can you please advice me for the solution?

**Comment by gotev** [comment]
It means Google Voice Search was unable to recognize what's being said. It may happen in offline mode or when using a least supported language by Google.
